[package]
name = "hotdog"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bottlerocket-os/hotdog/archive/v1.0.6/hotdog-1.0.6.tar.gz"
sha512 = "e6d0031c83a38547ea174d5518a4eb2b1d85467e9c5b0afab54ee1e6e54315abdffcee148ab15f41086dfc3d623ec329d11aa98d6e1864bba3472456579eafb6"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }

[dependencies]
log4j2-hotpatch= { path = "../log4j2-hotpatch" }
