[package]
name = "settings-committer"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
snafu = "0.5"
http = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4"
stderrlog = "0.4"

[build-dependencies]
cargo-readme = "3.1"
