[package]
name = "generate-readme"
version = "0.1.0"
authors = ["Matt Briggs <brigmatt@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
cargo-readme = "3"
snafu = "0.7"
