[package]
name = "ncurses"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://invisible-mirror.net/archives/ncurses/current/ncurses-6.1-20180923.tgz"
sha512 = "63709722949b013b07ec760db5006cdbafa1c75dee056f5206aa3031706fd5eb57342e99e0c29ce154646979aa7fc6d8c80f8a0e8debf128655d147b6a80c7b8"

[build-dependencies]
glibc = { path = "../glibc" }
