[package]
# This is the aws-k8s-1.29 variant. "." is not allowed in crate names, but we
# don't use this crate name anywhere.
name = "aws-k8s-1_29"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-features]
grub-set-private-var = true
uefi-secure-boot = true
xfs-data-partition = true
systemd-networkd = true

[package.metadata.build-variant]
included-packages = [
# core
    "release",
    "kernel-6.1",
# k8s
    "cni",
    "cni-plugins",
    "kubelet-1.29",
    "aws-iam-authenticator",
]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]

[lib]
path = "../variants.rs"

[build-dependencies]
settings-defaults = { path = "../../packages/settings-defaults" }
settings-plugins = { path = "../../packages/settings-plugins" }
settings-migrations = { path = "../../packages/settings-migrations" }
