[package]
# This is the nutanix-k8s-1.25 variant. "." is not allowed in crate names, but
# we don't use this crate name anywhere.
name = "nutanix-k8s-1_25"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-layout]
partition-plan = "unified"

[package.metadata.build-variant.image-features]
grub-set-private-var = true

[package.metadata.build-variant]
image-format = "qcow2"
supported-arches = ["x86_64"]
kernel-parameters = [
    "console=tty0",
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
]
included-packages = [
    "cni",
    "cni-plugins",
    "kernel-5.15",
    "kubelet-1.25",
    "release",
]

[lib]
path = "lib.rs"

[build-dependencies]
cni = { path = "../../packages/cni" }
cni-plugins = { path = "../../packages/cni-plugins" }
kernel-5_15 = { path = "../../packages/kernel-5.15" }
kubernetes-1_25 = { path = "../../packages/kubernetes-1.25" }
release = { path = "../../packages/release" }
