version = "1.0.5"

[migrations]
"(0.3.1, 0.3.2)" = ["migrate_v0.3.2_admin-container-v0-5-0.lz4"]
"(0.3.2, 0.3.3)" = []
"(0.3.3, 0.3.4)" = []
"(0.3.4, 0.4.0)" = []
"(0.4.0, 0.4.1)" = ["migrate_v0.4.1_add-version-lock-ignore-waves.lz4", "migrate_v0.4.1_pivot-repo-2020-07-07.lz4"]
"(0.4.1, 0.5.0)" = ["migrate_v0.5.0_add-cluster-domain.lz4", "migrate_v0.5.0_admin-container-v0-5-2.lz4", "migrate_v0.5.0_control-container-v0-4-1.lz4"]
"(0.5.0, 1.0.0)" = ["migrate_v1.0.0_ecr-helper-admin.lz4", "migrate_v1.0.0_ecr-helper-control.lz4"]
"(1.0.0, 1.0.1)" = []
"(1.0.1, 1.0.2)" = ["migrate_v1.0.2_add-enable-spot-instance-draining.lz4"]
"(1.0.2, 1.0.3)" = ["migrate_v1.0.3_add-sysctl.lz4"]
"(1.0.3, 1.0.4)" = []
"(1.0.4, 1.0.5)" = [
    "migrate_v1.0.5_add-lockdown.lz4",
    "migrate_v1.0.5_sysctl-subcommand.lz4",
    "migrate_v1.0.5_add-user-data.lz4",
    "migrate_v1.0.5_add-network-settings.lz4",
    "migrate_v1.0.5_add-proxy-restart.lz4",
    "migrate_v1.0.5_add-proxy-services.lz4"
]
"(1.0.5, 1.0.6)" = ["migrate_v1.0.6_metricdog-init.lz4", "migrate_v1.0.6_add-static-pods.lz4"]

