version = "1.17.0"

[migrations]
"(0.3.1, 0.3.2)" = ["migrate_v0.3.2_admin-container-v0-5-0.lz4"]
"(0.3.2, 0.3.3)" = []
"(0.3.3, 0.3.4)" = []
"(0.3.4, 0.4.0)" = []
"(0.4.0, 0.4.1)" = ["migrate_v0.4.1_add-version-lock-ignore-waves.lz4", "migrate_v0.4.1_pivot-repo-2020-07-07.lz4"]
"(0.4.1, 0.5.0)" = ["migrate_v0.5.0_add-cluster-domain.lz4", "migrate_v0.5.0_admin-container-v0-5-2.lz4", "migrate_v0.5.0_control-container-v0-4-1.lz4"]
"(0.5.0, 1.0.0)" = ["migrate_v1.0.0_ecr-helper-admin.lz4", "migrate_v1.0.0_ecr-helper-control.lz4"]
"(1.0.0, 1.0.1)" = []
"(1.0.1, 1.0.2)" = ["migrate_v1.0.2_add-enable-spot-instance-draining.lz4"]
"(1.0.2, 1.0.3)" = ["migrate_v1.0.3_add-sysctl.lz4"]
"(1.0.3, 1.0.4)" = []
"(1.0.4, 1.0.5)" = [
    "migrate_v1.0.5_add-lockdown.lz4",
    "migrate_v1.0.5_sysctl-subcommand.lz4",
    "migrate_v1.0.5_add-user-data.lz4",
    "migrate_v1.0.5_add-network-settings.lz4",
    "migrate_v1.0.5_add-proxy-restart.lz4",
    "migrate_v1.0.5_add-proxy-services.lz4",
]
"(1.0.5, 1.0.6)" = [
    "migrate_v1.0.6_metricdog-init.lz4",
    "migrate_v1.0.6_add-static-pods.lz4",
    "migrate_v1.0.6_kubelet-standalone-tls-settings.lz4",
    "migrate_v1.0.6_kubelet-standalone-tls-services.lz4",
    "migrate_v1.0.6_control-container-v0-4-2.lz4",
    "migrate_v1.0.6_add-shibaken.lz4",
    "migrate_v1.0.6_admin-container-v0-6-0.lz4",
]
"(1.0.6, 1.0.7)" = []
"(1.0.7, 1.0.8)" = [
    "migrate_v1.0.8_kubelet-eviction-hard.lz4",
    "migrate_v1.0.8_kubelet-unsafe-sysctl-kube-reserved.lz4",
    "migrate_v1.0.8_proxy-affect-host-containers.lz4",
    "migrate_v1.0.8_control-container-v0-5-0.lz4",
    "migrate_v1.0.8_admin-container-v0-7-0.lz4",
    "migrate_v1.0.8_add-bootstrap-containers.lz4"
]
"(1.0.8, 1.1.0)" = [
    "migrate_v1.1.0_kubelet-server-tls-bootstrap.lz4",
    "migrate_v1.1.0_kubelet-cloud-provider.lz4",
    "migrate_v1.1.0_kubelet-registry-qps-registry-burst.lz4",
    "migrate_v1.1.0_shared-containerd-configs.lz4",
    "migrate_v1.1.0_kubelet-event-qps-event-burst.lz4",
    "migrate_v1.1.0_schnauzer-paws.lz4",
    "migrate_v1.1.0_kubelet-kube-api-qps-kube-api-burst.lz4",
]
"(1.1.0, 1.1.1)" = []
"(1.1.1, 1.1.2)" = [
    "migrate_v1.1.2_kubelet-container-log.lz4",
    "migrate_v1.1.2_kubelet-system-reserved.lz4",
    "migrate_v1.1.2_admin-container-v0-7-1.lz4",
    "migrate_v1.1.2_control-container-v0-5-1.lz4",
]
"(1.1.2, 1.1.3)" = [
    "migrate_v1.1.3_kubelet-cpu-manager-state.lz4",
    "migrate_v1.1.3_kubelet-cpu-manager.lz4",
]
"(1.1.3, 1.1.4)" = []
"(1.1.4, 1.2.0)" = [
    "migrate_v1.2.0_hostname-setting.lz4",
    "migrate_v1.2.0_hostname-setting-metadata.lz4",
    "migrate_v1.2.0_add-custom-certificates.lz4",
    "migrate_v1.2.0_kubelet-topology-manager.lz4",
    "migrate_v1.2.0_container-registry-mirrors.lz4",
    "migrate_v1.2.0_container-registry-config-restarts.lz4",
    "migrate_v1.2.0_admin-container-v0-7-2.lz4",
]
"(1.2.0, 1.2.1)" = []
"(1.2.1, 1.3.0)" = [
    "migrate_v1.3.0_etc-hosts-service.lz4",
    "migrate_v1.3.0_hostname-affects-etc-hosts.lz4",
    "migrate_v1.3.0_control-container-v0-5-2.lz4",
]
"(1.3.0, 1.4.0)" = [
    "migrate_v1.4.0_registry-mirror-representation.lz4",
]
"(1.4.0, 1.4.1)" = []
"(1.4.1, 1.4.2)" = [
    "migrate_v1.4.2_admin-container-v0-7-3.lz4",
    "migrate_v1.4.2_control-container-v0-5-3.lz4",
]
"(1.4.2, 1.5.0)" = [
    "migrate_v1.5.0_oci-hooks-setting.lz4",
    "migrate_v1.5.0_oci-hooks-setting-metadata.lz4",
]
"(1.5.0, 1.5.1)" = [
    "migrate_v1.5.1_control-container-v0-5-4.lz4",
]
"(1.5.1, 1.5.2)" = []
"(1.5.2, 1.5.3)" = [
    "migrate_v1.5.3_vmware-host-containers.lz4",
]
"(1.5.3, 1.6.0)" = [
    "migrate_v1.6.0_node-taints-representation.lz4",
    "migrate_v1.6.0_aws-admin-container-v0-7-4.lz4",
    "migrate_v1.6.0_aws-control-container-v0-5-5.lz4",
    "migrate_v1.6.0_public-admin-container-v0-7-4.lz4",
    "migrate_v1.6.0_public-control-container-v0-5-5.lz4",
]
"(1.6.0, 1.6.1)" = []
"(1.6.1, 1.6.2)" = [
    "migrate_v1.6.2_add-cfsignal.lz4",
    "migrate_v1.6.2_container-registry-credentials.lz4",
    "migrate_v1.6.2_container-registry-credentials-metadata.lz4",
]
"(1.6.2, 1.7.0)" = [
    "migrate_v1.7.0_aws-admin-container-v0-8-0.lz4",
    "migrate_v1.7.0_aws-control-container-v0-6-0.lz4",
    "migrate_v1.7.0_public-admin-container-v0-8-0.lz4",
    "migrate_v1.7.0_public-control-container-v0-6-0.lz4",
]
"(1.7.0, 1.7.1)" = []
"(1.7.1, 1.7.2)" = []
"(1.7.2, 1.8.0)" = [
    "migrate_v1.8.0_boot-setting.lz4",
    "migrate_v1.8.0_boot-setting-metadata.lz4",
    "migrate_v1.8.0_kubelet-pod-pids-limit.lz4",
    "migrate_v1.8.0_add-pull-behavior.lz4",
    "migrate_v1.8.0_add-autoscaling.lz4",
    "migrate_v1.8.0_etc-hosts.lz4",
    "migrate_v1.8.0_etc-hosts-metadata.lz4",
    "migrate_v1.8.0_cluster-dns-ip-list.lz4",
    "migrate_v1.8.0_pki-affected-services.lz4",
    "migrate_v1.8.0_kubelet-provider-id.lz4",
    "migrate_v1.8.0_aws-admin-container-v0-9-0.lz4",
    "migrate_v1.8.0_aws-control-container-v0-6-1.lz4",
    "migrate_v1.8.0_public-admin-container-v0-9-0.lz4",
    "migrate_v1.8.0_public-control-container-v0-6-1.lz4",
]
"(1.8.0, 1.9.0)" = [
    "migrate_v1.9.0_ntp-affected-services.lz4",
    "migrate_v1.9.0_shibaken-admin-userdata-semantics.lz4",
    "migrate_v1.9.0_shibaken-send-metrics.lz4",
    "migrate_v1.9.0_image-gc-thresholds.lz4",
    "migrate_v1.9.0_kernel-modules-setting.lz4",
    "migrate_v1.9.0_kernel-modules-setting-metadata.lz4",
    "migrate_v1.9.0_kubelet-no-daemon-reload.lz4",
    "migrate_v1.9.0_updates-targets-base-url.lz4",
]
"(1.9.0, 1.9.1)" = []
"(1.9.1, 1.9.2)" = []
"(1.9.2, 1.10.0)" = [
    "migrate_v1.10.0_dns-settings.lz4",
    "migrate_v1.10.0_dns-settings-metadata.lz4",
    "migrate_v1.10.0_reboot-to-reconcile-setting.lz4",
    "migrate_v1.10.0_kubelet-log-level.lz4",
    "migrate_v1.10.0_aws-admin-container-v0-9-2.lz4",
    "migrate_v1.10.0_public-admin-container-v0-9-2.lz4",
    "migrate_v1.10.0_aws-control-container-v0-6-3.lz4",
    "migrate_v1.10.0_public-control-container-v0-6-3.lz4"
]
"(1.10.0, 1.10.1)" = [
    "migrate_v1.10.1_container-runtime.lz4",
    "migrate_v1.10.1_container-runtime-metadata.lz4"
]
"(1.10.1, 1.11.0)" = [
    "migrate_v1.11.0_aws-config-settings.lz4",
    "migrate_v1.11.0_aws-creds.lz4",
    "migrate_v1.11.0_aws-creds-metadata.lz4",
    "migrate_v1.11.0_credential-providers.lz4",
    "migrate_v1.11.0_kubelet-tls-config.lz4",
    "migrate_v1.11.0_kubelet-tls-files.lz4",
    "migrate_v1.11.0_kubelet-new-config-files.lz4",
    "migrate_v1.11.0_ecs-additional-configurations.lz4",
    "migrate_v1.11.0_aws-admin-container-v0-9-3.lz4",
    "migrate_v1.11.0_public-admin-container-v0-9-3.lz4",
    "migrate_v1.11.0_aws-control-container-v0-6-4.lz4",
    "migrate_v1.11.0_public-control-container-v0-6-4.lz4",
]
"(1.11.0, 1.11.1)" = []
"(1.11.1, 1.12.0)" = [
    "migrate_v1.12.0_k8s-private-pki-path.lz4",
    "migrate_v1.12.0_add-k8s-autoscaling-warm-pool-setting.lz4",
    "migrate_v1.12.0_add-k8s-autoscaling-warm-pool-setting-metadata.lz4",
    "migrate_v1.12.0_oci-defaults-setting.lz4",
    "migrate_v1.12.0_oci-defaults-setting-metadata.lz4",
    "migrate_v1.12.0_aws-admin-container-v0-9-4.lz4",
    "migrate_v1.12.0_public-admin-container-v0-9-4.lz4",
    "migrate_v1.12.0_aws-control-container-v0-7-0.lz4",
    "migrate_v1.12.0_public-control-container-v0-7-0.lz4",
]
"(1.12.0, 1.13.0)" = [
    "migrate_v1.13.0_k8s-registry.lz4",
    "migrate_v1.13.0_aws-admin-container-v0-10-0.lz4",
    "migrate_v1.13.0_public-admin-container-v0-10-0.lz4",
    "migrate_v1.13.0_aws-control-container-v0-7-1.lz4",
    "migrate_v1.13.0_public-control-container-v0-7-1.lz4",
]
"(1.13.0, 1.13.1)" = [
    "migrate_v1.13.1_aws-profile-cred-provider.lz4",
]
"(1.13.1, 1.13.2)" = []
"(1.13.2, 1.13.3)" = [
    "migrate_v1.13.3_aws-k8s-provider-id-gen.lz4",
]
"(1.13.3, 1.13.4)" = [
    "migrate_v1.13.4_add-hostname-override.lz4",
    "migrate_v1.13.4_add-hostname-override-metadata.lz4",
]
"(1.13.4, 1.13.5)" = []
"(1.13.5, 1.14.0)" = [
    "migrate_v1.14.0_kubernetes-gc-percent-type-change.lz4",
    "migrate_v1.14.0_kubelet-config-settings.lz4",
    "migrate_v1.14.0_kubelet-prefix-config-settings.lz4",
    "migrate_v1.14.0_k8s-services-mode.lz4",
    "migrate_v1.14.0_aws-admin-container-v0-10-1.lz4",
    "migrate_v1.14.0_public-admin-container-v0-10-1.lz4",
    "migrate_v1.14.0_aws-control-container-v0-7-2.lz4",
    "migrate_v1.14.0_public-control-container-v0-7-2.lz4",
]
"(1.14.0, 1.14.1)" = []
"(1.14.1, 1.14.2)" = [
    "migrate_v1.14.2_ecs-images-cleanup.lz4",
]
"(1.14.2, 1.14.3)" = [
    "migrate_v1.14.3_aws-admin-container-v0-10-2.lz4",
    "migrate_v1.14.3_public-admin-container-v0-10-2.lz4",
    "migrate_v1.14.3_aws-control-container-v0-7-3.lz4",
    "migrate_v1.14.3_public-control-container-v0-7-3.lz4",
]
"(1.14.3, 1.15.0)" = [
    "migrate_v1.15.0_oci-defaults-resource-setting.lz4",
    "migrate_v1.15.0_oci-defaults-max-open-files.lz4",
    "migrate_v1.15.0_seccomp-default-setting.lz4",
    "migrate_v1.15.0_oci-defaults-docker-setting.lz4",
    "migrate_v1.15.0_oci-defaults-docker-setting-metadata.lz4",
    "migrate_v1.15.0_aws-admin-container-v0-11-0.lz4",
    "migrate_v1.15.0_public-admin-container-v0-11-0.lz4",
    "migrate_v1.15.0_aws-control-container-v0-7-4.lz4",
    "migrate_v1.15.0_public-control-container-v0-7-4.lz4",
    "migrate_v1.15.0_log4j-hotpatch-enabled-metadata.lz4",
    "migrate_v1.15.0_deprecate-log4j-hotpatch-enabled.lz4",
]
"(1.15.0, 1.15.1)" = []
"(1.15.1, 1.16.0)" = [
    "migrate_v1.16.0_kernel-modules-autoload-configs.lz4",
    "migrate_v1.16.0_kernel-modules-autoload-files.lz4",
    "migrate_v1.16.0_kernel-modules-autoload-restart.lz4",
    "migrate_v1.16.0_kernel-modules-autoload-settings.lz4",
    "migrate_v1.16.0_aws-admin-container-v0-11-1.lz4",
    "migrate_v1.16.0_public-admin-container-v0-11-1.lz4",
    "migrate_v1.16.0_aws-control-container-v0-7-5.lz4",
    "migrate_v1.16.0_public-control-container-v0-7-5.lz4",
    "migrate_v1.16.0_schnauzer-v2-generators.lz4",
]
"(1.16.0, 1.16.1)" = [
    "migrate_v1.16.1_updog-network-affected.lz4",
]
"(1.16.1, 1.17.0)" = [
    "migrate_v1.17.0_aws-admin-container-v0-11-2.lz4",
    "migrate_v1.17.0_public-admin-container-v0-11-2.lz4",
    "migrate_v1.17.0_aws-control-container-v0-7-6.lz4",
    "migrate_v1.17.0_public-control-container-v0-7-6.lz4",
]
