schema-version = 1
release-version = "1.18.0"

[sdk]
registry = "public.ecr.aws/bottlerocket"
name = "bottlerocket-sdk"
version = "v0.37.0"

[toolchain]
registry = "public.ecr.aws/bottlerocket"
name = "bottlerocket-toolchain"
version = "v0.37.0"
