schema-version = 1
release-version = "1.21.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.43.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "2.3.0"
vendor = "bottlerocket"
