[package]
name = "ca-certificates"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
releases-url = "https://curl.se/docs/caextract.html"

[[package.metadata.build-package.external-files]]
url = "https://curl.haxx.se/ca/cacert-2023-01-10.pem"
sha512 = "08cd35277bf2260cb3232d7a7ca3cce6b2bd58af9221922d2c6e9838a19c2f96d1ca6d77f3cc2a3ab611692f9fec939e9b21f67442282e867a487b0203ee0279"
