[package]
name = "thar-be-settings"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiserver = { path = "../apiserver" }
base64 = "0.10"
handlebars = "2.0"
itertools = "0.8"
log = "0.4"
reqwest = { version = "0.9", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
snafu = "0.4"
stderrlog = "0.4"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
