[settings.host-containers.admin]
enabled = false
superpowered = true

[metadata.settings.host-containers.admin.source]
setting-generator = "schnauzer-v2 render --requires 'aws@v1(helpers=[ecr-prefix])' --template '{{ ecr-prefix settings.aws.region }}/bottlerocket-admin:v0.11.4'"

[metadata.settings.host-containers.admin.user-data]
setting-generator = "shibaken generate-admin-userdata"

[settings.host-containers.control]
enabled = true
superpowered = false

[metadata.settings.host-containers.control.source]
setting-generator = "schnauzer-v2 render --requires 'aws@v1(helpers=[ecr-prefix])' --template '{{ ecr-prefix settings.aws.region }}/bottlerocket-control:v0.7.8'"
