[settings.kubernetes]
cluster-domain = "cluster.local"
standalone-mode = false
authentication-mode = "tls"
pod-infra-container-image = "public.ecr.aws/eks-distro/kubernetes/pause:3.5"
server-tls-bootstrap = false
cloud-provider = ""

[metadata.settings.kubernetes]
node-ip.setting-generator = "netdog node-ip"
affected-services = ["kubernetes"]

# Metrics
[settings.metrics]
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "kubelet"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "kubernetes", "host-containerd", "host-containers", "updog"]
