# Both containers are disabled by default in VMware because the user must
# supply user data in order to use the containers.  The admin container isn't
# useful without SSH keys/CA certs, and the control container can only be used
# with hybrid SSM off of AWS.  VMware users might not want to use either of
# those options.
[settings.host-containers.admin]
enabled = false
superpowered = true
source = "public.ecr.aws/bottlerocket/bottlerocket-admin:v0.7.3"

[settings.host-containers.control]
enabled = false
superpowered = false
source = "public.ecr.aws/bottlerocket/bottlerocket-control:v0.5.2"
