[package]
name = "static-pods"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
constants = { path = "../../constants", version = "0.1.0" }
base64 = "0.13"
log = "0.4"
models = { path = "../../models", version = "0.1.0" }
schnauzer = { path = "../schnauzer", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.11"
snafu = "0.7"
tokio = { version = "~1.17", default-features = false, features = ["macros", "rt-multi-thread", "time"] }  # LTS
tempfile = "3.2.0"

[build-dependencies]
cargo-readme = "3.1"
