[package]
name = "settings-defaults-vmware-dev"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false
build = "../build-defaults.rs"

[lib]
path = "../defaults-toml.rs"

[build-dependencies.bottlerocket-defaults-helper]
git = "https://github.com/bottlerocket-os/bottlerocket-settings-sdk"
tag = "bottlerocket-defaults-helper-v0.1.0"
version = "0.1.0"
