[workspace]
members = [
    "aws-dev",
    "aws-ecs-1",
    "aws-ecs-1-nvidia",
    "aws-k8s-1.21",
    "aws-k8s-1.21-nvidia",
    "aws-k8s-1.22",
    "aws-k8s-1.22-nvidia",
    "aws-k8s-1.23",
    "aws-k8s-1.23-nvidia",
    "aws-k8s-1.24",
    "aws-k8s-1.24-nvidia",
    "metal-dev",
    "metal-k8s-1.21",
    "metal-k8s-1.22",
    "metal-k8s-1.23",
    "metal-k8s-1.24",
    "vmware-dev",
    "vmware-k8s-1.21",
    "vmware-k8s-1.22",
    "vmware-k8s-1.23",
    "vmware-k8s-1.24",
]

[profile.dev]
debug = false
opt-level = 'z'

[profile.dev.build-override]
opt-level = 'z'
