[workspace]
members = [
    "aws-dev",
    "aws-ecs-1",
    "aws-k8s-1.19",
    "aws-k8s-1.20",
    "aws-k8s-1.21",
    "aws-k8s-1.21-nvidia",
    "aws-k8s-1.22",
    "aws-k8s-1.22-nvidia",
    "metal-dev",
    "metal-k8s-1.21",
    "metal-k8s-1.22",
    "vmware-dev",
    "vmware-k8s-1.20",
    "vmware-k8s-1.21",
    "vmware-k8s-1.22",
]

[profile.dev]
debug = false
opt-level = 'z'

[profile.dev.build-override]
opt-level = 'z'
