[package]
name = "schnauzer"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[features]
default = []
testfakes = []

[dependencies]
apiclient = { path = "../apiclient", version = "0.1" }
argh = "0.1"
async-trait = "0.1"
base64 = "0.13"
cached = "0.44"
constants = { path = "../../constants", version = "0.1" }
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1" }
dns-lookup = "1"
handlebars = "4"
http = "0.2"
lazy_static = "1"
log = "0.4"
maplit = "1.0"
models = { path = "../../models", version = "0.1" }
num_cpus = "1"
percent-encoding = "2"
pest = "2.5"
pest_derive = "2.5"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
simplelog = "0.12"
snafu = "0.7"
tokio = { version = "~1.25", default-features = false, features = ["macros", "rt-multi-thread"] } # LTS
toml = "0.5"
url = "2"

[dev-dependencies]
# Workaround to enable a feature during integration tests.
schnauzer = { path = ".", version = "0.1.0", features = ["testfakes"] }

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }
