[package]
name = "schnauzer"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
base64 = "0.13"
bottlerocket-release = { path = "../../bottlerocket-release" }
handlebars = "3.0"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
models = { path = "../../models" }
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
snafu = "0.6"
tokio = { version = "0.2", default-features = false, features = ["macros", "rt-threaded"] }
url = "2.1"
# When hyper updates to tokio 0.3:
#tokio = { version = "0.3", default-features = false, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cargo-readme = "3.1"
