[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
actix = { version = "0.13.0", default-features = false, features = ["macros"] }
actix-rt = "2"
actix-web = { version = "4.0.1", default-features = false }
actix-web-actors = { version = "4.0.0", default-features = false }
bytes = "1.1"
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1.0" }
datastore = { path = "../datastore", version = "0.1.0" }
fs2 = "0.4.3"
futures = { version = "0.3", default-features = false }
http = "0.2.1"
libc = "0.2"
log = "0.4"
models = { path = "../../models", version = "0.1.0" }
nix = "0.23"
num = "0.4"
percent-encoding = "2.1"
rand = "0.8"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.11"
snafu = "0.7"
thar-be-updates = { path = "../thar-be-updates", version = "0.1.0" }
walkdir = "2.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
toml = "0.5"
