[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
actix-web = { version = "3.2.0", default-features = false }
bottlerocket-release = { path = "../../bottlerocket-release" }
datastore = { path = "../datastore" }
fs2 = "0.4.3"
futures = { version = "0.3", default-features = false }
http = "0.2.1"
libc = "0.2"
log = "0.4"
models = { path = "../../models" }
nix = "0.19.0"
num = "0.3.0"
percent-encoding = "2.1"
semver = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.9"
snafu = "0.6"
thar-be-updates = { path = "../thar-be-updates" }
walkdir = "2.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
toml = "0.5"
