[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
actix-web = { version = "1.0.5", default-features = false, features = ["uds"] }
bottlerocket-release = { path = "../../bottlerocket-release" }
libc = "0.2"
log = "0.4"
models = { path = "../../models" }
nix = "0.16.0"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.7"
snafu = "0.6"
walkdir = "2.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
toml = "0.5"
