[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
actix = { version = "0.13", default-features = false, features = ["macros"] }
actix-rt = "2"
actix-web = { version = "4", default-features = false }
actix-web-actors = { version = "4", default-features = false }
bytes = "1"
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1" }
datastore = { path = "../datastore", version = "0.1" }
fs2 = "0.4"
http = "0.2"
libc = "0.2"
log = "0.4"
models = { path = "../../models", version = "0.1" }
nix = "0.26"
num = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = "0.12"
snafu = "0.7"
thar-be-updates = { path = "../thar-be-updates", version = "0.1" }
tokio = { version = "~1.25", default-features = false, features = ["process"] }

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }

[dev-dependencies]
maplit = "1"
toml = "0.5"
