[package]
name = "glibc"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/glibc"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/glibc/glibc-2.37.tar.xz"
sha512 = "4fc5932f206bb1b8b54828a28af1a681616b838bbab60c81c82155f3629cbfe1301d271af65511ed917f4c6949a025429221fe6035753282f15346919f15b90c"
