[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"
# Changelog can be found here: https://sites.google.com/site/fullycapable/release-notes-for-libcap

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.67.tar.gz"
sha512 = "d182b8656522aa0d5516186df1164bc0375dd0650d59bb6807997d4ba4e6ccb427d7c6d30cc3d459240fcfd4c550d31ebde892b03f8bbd80cc43a2a226b4b151"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
