[package]
name = "libcap"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"
# Changelog can be found here: https://sites.google.com/site/fullycapable/release-notes-for-libcap

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.68.tar.gz"
sha512 = "b5dbf42790114cb26d923f8a7f40a44fc1ac370eac6f7cfc0c0bfed870648e501f920295159c4ab906b7df66d662add04938b1fe9998dc403be81aec95234bf3"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
