[package]
name = "migrator"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
data_store_version = { path = "../../data_store_version" }
fs_extra = "1.1"
lazy_static = "1.2"
log = "0.4"
nix = "0.15"
rand = { version = "0.7", default-features = false, features = ["std"] }
regex = "1.1"
simplelog = "0.7"
snafu = "0.5"

[build-dependencies]
cargo-readme = "3.1"

[lib]
name = "migrator"
path = "src/lib.rs"

[[bin]]
name = "migrator"
path = "src/main.rs"
