[package]
name = "migration-helpers"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
apiserver = { path = "../../apiserver" }
schnauzer = { path = "../../schnauzer" }
handlebars = "3.0.1"
snafu = "0.6"
toml = "0.5"
serde_json = "1.0"
serde = "1.0.104"

[dev-dependencies]
maplit = "1.0"
