[package]
name = "migration-helpers"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bottlerocket-release = { path = "../../../bottlerocket-release", version = "0.1.0" }
datastore = { path = "../../datastore", version = "0.1.0" }
handlebars = "4.1"
schnauzer = { path = "../../schnauzer", version = "0.1.0" }
serde = "1.0.104"
serde_json = "1.0"
snafu = "0.7"
toml = "0.5"

[dev-dependencies]
maplit = "1.0"
