[package]
name = "migration-helpers"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bottlerocket-release.workspace = true
datastore.workspace = true
handlebars.workspace = true
schnauzer.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[dev-dependencies]
maplit.workspace = true
