[package]
name = "iproute"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "http://kernel.org/pub/linux/utils/net/iproute2"

[[package.metadata.build-package.external-files]]
url = "https://kernel.org/pub/linux/utils/net/iproute2/iproute2-6.2.0.tar.xz"
sha512 = "b24e0fdd0f51b8b78bc3bb681e3829af47d3011e93f3892289eb070b336709a6883728ecc7627ca37f6449720f8ed1349af321c0d04454894a7175b82f7de151"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libmnl = { path = "../libmnl" }
libselinux = { path = "../libselinux" }
