[services.kubernetes]
configuration-files = [
  "kubelet-env",
  "kubelet-config",
  "kubelet-kubeconfig",
  "kubelet-bootstrap-kubeconfig",
  "kubelet-exec-start-conf",
  "kubernetes-ca-crt",
  "proxy-env",
  "kubelet-server-crt",
  "kubelet-server-key",
  "credential-provider-config-yaml",
]
restart-commands = [
  "/usr/bin/systemctl try-restart kubelet.service"
]

[configuration-files.kubelet-env]
path = "/etc/kubernetes/kubelet/env"
template-path = "/usr/share/templates/kubelet-env"

[configuration-files.kubelet-config]
path = "/etc/kubernetes/kubelet/config"
template-path = "/usr/share/templates/kubelet-config"
mode = "0600"

[configuration-files.kubelet-kubeconfig]
path = "/etc/kubernetes/kubelet/kubeconfig"
template-path = "/usr/share/templates/kubelet-kubeconfig"
mode = "0600"

[configuration-files.kubelet-bootstrap-kubeconfig]
path = "/etc/kubernetes/kubelet/bootstrap-kubeconfig"
template-path = "/usr/share/templates/kubelet-bootstrap-kubeconfig"
mode = "0600"

[configuration-files.kubernetes-ca-crt]
path = "/etc/kubernetes/pki/ca.crt"
template-path = "/usr/share/templates/kubernetes-ca-crt"
mode = "0600"

[configuration-files.kubelet-server-crt]
path = "/etc/kubernetes/pki/kubelet-server.crt"
template-path = "/usr/share/templates/kubelet-server-crt"

[configuration-files.kubelet-server-key]
path = "/etc/kubernetes/pki/private/kubelet-server.key"
template-path = "/usr/share/templates/kubelet-server-key"

[configuration-files.kubelet-exec-start-conf]
path = "/etc/systemd/system/kubelet.service.d/exec-start.conf"
template-path = "/usr/share/templates/kubelet-exec-start-conf"
mode = "0600"

[configuration-files.credential-provider-config-yaml]
path = "/etc/kubernetes/kubelet/credential-provider-config.yaml"
template-path = "/usr/share/templates/credential-provider-config-yaml"
mode = "0600"

[configuration-files.static-pods-toml]
path = "/etc/kubernetes/static-pods-manifest.toml"
template-path = "/usr/share/templates/static-pods-toml"

[services.static-pods]
configuration-files = ["static-pods-toml"]
restart-commands = ["/usr/bin/static-pods"]

[metadata.settings.kubernetes.static-pods]
affected-services = ["static-pods"]

[metadata.settings.aws.profile]
affected-services = ["kubernetes"]
