[package]
name = "liblzma"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://tukaani.org/xz"

[[package.metadata.build-package.external-files]]
url = "https://tukaani.org/xz/xz-5.4.2.tar.xz"
sha512 = "39163ee327743111968c4231fccc4ebbc1c77c96acf19afa8b1ca4153826a2c0d83b43111fa22b56139c03fc19c621d365fa0f80be1f3c3784fe7dd6f8fcfb68"

[build-dependencies]
glibc = { path = "../glibc" }
