[package]
name = "signpost"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
bit_field = "0.10.0"
block-party = { path = "../block-party" }
gptman = { version = "0.6.1", default-features = false }
hex-literal = "0.2.0"
serde = { version = "1.0.91", features = ["derive"] }
serde_plain = "0.3.0"
snafu = { version = "0.6.0", default-features = false, features = ["std"] }
