[package]
name = "infrasys"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
authors = ["Aashna Sheth <shetaash@amazon.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
log = "0.4"
pubsys-config = { path = "../pubsys-config/", version = "0.1" }
aws-config = "0.55"
aws-types = "0.55"
aws-sdk-cloudformation = "0.28"
aws-sdk-s3 = "0.28"
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10"
shell-words = "1"
simplelog = "0.12"
snafu = "0.7"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }
url = "2"

[dev-dependencies]
assert-json-diff = "2"
