[package]
name = "public-admin-container-v0-11-3"
version = "0.1.0"
authors = ["Markus Boehme <markubo@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
migration-helpers = { path = "../../../migration-helpers", version = "0.1.0"}
