[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
derive-error = "0.0"
lazy_static = "1.2"
log = "0.4"
regex = "1.1"
rouille = { version = "3.0", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
stderrlog = "0.4"
toml = "0.5"
walkdir = "2.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
