[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
releases-url = "https://github.com/besser82/libxcrypt/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/releases/download/v4.4.33/libxcrypt-4.4.33.tar.xz"
sha512 = "b46d226a83d35b578381aa340e34cd77aea25a304aec3d00ba3d3acb6462e96824ff82ea930aaf2b87039dfffef4dab4b1774736d6b8a107cfb61e6cdb307b99"

[build-dependencies]
glibc = { path = "../glibc" }
