[package]
name = "libxcrypt"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/besser82/libxcrypt/archive/v4.4.3/libxcrypt-4.4.3.tar.gz"
sha512 = "c919ded5fcb84e21a0972bb5521aa155471ef11da4478afc31b843c1e55031a16125838883640b0c19eb6e1f717d76d15201ecf3ae5338c5905fe4a807386066"

[build-dependencies]
glibc = { path = "../glibc" }
