[package]
name = "grep"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.kernel.org/gnu/grep"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.kernel.org/gnu/grep/grep-3.8.tar.xz"
sha512 = "2014519a80c6dcd799837e1bd7d9d5ebe8729ec54b0dc76981dac4755a9a8a9f200470cdcc911e2825bed8162e61da39e3dd60289f7393b48bf67314077d0c79"

[dependencies]
libpcre = { path = "../libpcre" }

[build-dependencies]
libpcre = { path = "../libpcre" }
glibc = { path = "../glibc" }
