[package]
name = "olpc-cjson"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
serde = "1.0"
serde_json = "1.0.29"
unicode-normalization = "0.1"
