[package]
name = "thar-be-updates"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient", version = "0.1" }
constants = { path = "../../constants", version = "0.1" }
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1" }
chrono = { version = "0.4", default-features = false, features = ["std", "serde", "clock"] }
fs2 = "0.4"
http = "0.2"
log = "0.4"
models = { path = "../../models", version = "0.1" }
nix = "0.26"
num-derive = "0.3"
num-traits = "0.2"
semver = { version = "1", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_plain = "1"
signpost = { path = "../../updater/signpost", version = "0.1" }
simplelog = "0.12"
snafu = "0.7"
tempfile = "3"
tokio = { version = "~1.25", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS
update_metadata = { path = "../../updater/update_metadata", version = "0.1" }

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }
