[package]
name = "thar-be-updates"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
bottlerocket-release = { path = "../../bottlerocket-release" }
chrono = { version = "0.4.11", features = [ "serde" ] }
fs2 = "0.4.3"
http = "0.2.1"
log = "0.4.8"
models = { path = "../../models" }
nix = "0.19.0"
num-derive = "0.3.0"
num-traits = "0.2.12"
semver = { version = "0.11", features = [ "serde" ] }
serde = { version = "1.0.111", features = [ "derive" ] }
serde_json = "1.0.53"
serde_plain = "0.3.0"
signpost = { path = "../../updater/signpost" }
simplelog = "0.9"
snafu = "0.6.8"
tempfile = "3.1.0"
tokio = { version = "0.2", default-features = false, features = ["macros", "rt-threaded"] }
# When hyper updates to tokio 0.3:
#tokio = { version = "0.3", default-features = false, features = ["macros", "rt-multi-thread"] }
update_metadata = { path = "../../updater/update_metadata" }

[build-dependencies]
cargo-readme = "3.1"
