[package]
name = "buildsys"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
duct = "0.13.0"
hex = "0.4.0"
rand = { version = "0.7", default-features = false, features = ["std"] }
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
sha2 = "0.9"
snafu = "0.6"
toml = "0.5"
url = { version = "2.1.0", features = ["serde"] }
walkdir = "2"
nonzero_ext = "0.2.0"
