[package]
name = "aws-ecs-1"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-variant]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "systemd.unified_cgroup_hierarchy=0",
    "quiet",
]
included-packages = [
# core
    "release",
    "kernel-5.10",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
# ecs
    "ecs-agent-config",
]

[lib]
path = "../variants.rs"

[build-dependencies]
settings-defaults = { path = "../../packages/settings-defaults" }
settings-plugins = { path = "../../packages/settings-plugins" }
