[package]
name = "pubsys"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1.36"
chrono = "0.4"
clap = "2.33"
coldsnap = "0.1"
futures = "0.3.5"
indicatif = "0.15.0"
lazy_static = "1.4"
log = "0.4"
parse-datetime = { path = "../../sources/parse-datetime" }
# Need to bring in reqwest with a TLS feature so tough can support TLS repos.
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls", "blocking"] }
rusoto_core = "0.45.0"
rusoto_credential = "0.45.0"
rusoto_ebs = "0.45.0"
rusoto_ec2 = "0.45.0"
rusoto_signature = "0.45.0"
rusoto_sts = "0.45.0"
simplelog = "0.8"
snafu = "0.6"
semver = "0.10.0"
serde = { version = "1.0", features = ["derive"]  }
serde_json = "1.0"
structopt = { version = "0.3", default-features = false  }
tokio = "0.2.21"
toml = "0.5"
tough = { version = "0.8", features = ["http"] }
tough-ssm = "0.3"
update_metadata = { path = "../../sources/updater/update_metadata/" }
url = { version = "2.1.0", features = ["serde"] }
tempfile = "3.1"
