[package]
name = "pubsys"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1.36"
chrono = "0.4"
clap = "2.33"
coldsnap = { version = "0.3", default-features = false, features = ["rusoto-rustls"]}
duct = "0.13.0"
pubsys-config = { path = "../pubsys-config/" }
futures = "0.3.5"
indicatif = "0.16.0"
lazy_static = "1.4"
log = "0.4"
num_cpus = "1"
parse-datetime = { path = "../../sources/parse-datetime" }
rayon = "1"
# Need to bring in reqwest with a TLS feature so tough can support TLS repos.
reqwest = { version = "0.11.1", default-features = false, features = ["rustls-tls", "blocking"] }
rusoto_core = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_credential = "0.47.0"
rusoto_ebs = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_ec2 = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_kms = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_signature = "0.47.0"
rusoto_ssm = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_sts = { version = "0.47.0", default-features = false, features = ["rustls"] }
simplelog = "0.10.0"
snafu = "0.6"
semver = "1.0"
serde = { version = "1.0", features = ["derive"]  }
serde_json = "1.0"
structopt = { version = "0.3", default-features = false  }
tinytemplate = "1.1"
tokio = { version = "~1.8", features = ["full"] }  # LTS
tokio-stream = { version = "0.1", features = ["time"] }
toml = "0.5"
tough = { version = "0.11", features = ["http"] }
tough-kms = "0.3"
tough-ssm = "0.6"
update_metadata = { path = "../../sources/updater/update_metadata/" }
url = { version = "2.1.0", features = ["serde"] }
tempfile = "3.1"
