[package]
name = "pubsys-config"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
home = "0.5"
lazy_static = "1"
log = "0.4"
parse-datetime = { path = "../../sources/parse-datetime", version = "0.1" }
serde = { version = "1", features = ["derive"]  }
serde_yaml = "0.8"
snafu = "0.7"
toml = "0.5"
url = { version = "2", features = ["serde"] }
