[package]
name = "servicedog"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
apiserver = { path = "../apiserver" }
http = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.7"
snafu = "0.5"

[build-dependencies]
cargo-readme = "3.1"
