[package]
# This is the aws-k8s-1.21 variant.  "." is not allowed in crate names, but we
# don't use this crate name anywhere.
name = "aws-k8s-1_21"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant]
included-packages = [
    "aws-iam-authenticator",
    "cni",
    "cni-plugins",
    "kernel-5.10",
    "kubelet-1.21",
    "release",
]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]

[lib]
path = "lib.rs"

[build-dependencies]
aws-iam-authenticator = { path = "../../packages/aws-iam-authenticator" }
cni = { path = "../../packages/cni" }
cni-plugins = { path = "../../packages/cni-plugins" }
kernel-5_10 = { path = "../../packages/kernel-5.10" }
kubernetes-1_21 = { path = "../../packages/kubernetes-1.21" }
release = { path = "../../packages/release" }
