[package]
# This is the aws-k8s-1.20 variant.  "." is not allowed in crate names, but we
# don't use this crate name anywhere.
name = "aws-k8s-1_20"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant]
included-packages = [
    "aws-iam-authenticator",
    "cni",
    "cni-plugins",
    "kubelet-1.20",
    "release",
]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0",
    "systemd.unified_cgroup_hierarchy=1",
]

[lib]
path = "lib.rs"

[build-dependencies]
"aws-iam-authenticator" = { path = "../../packages/aws-iam-authenticator" }
"cni" = { path = "../../packages/cni" }
"cni-plugins" = { path = "../../packages/cni-plugins" }
"kubernetes-1_20" = { path = "../../packages/kubernetes-1.20" }
"release" = { path = "../../packages/release" }
