[package]
name = "vmware-cd-rom-user-data-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
base64 = "0.21"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.6"
snafu = "0.8"
early-boot-config-provider = { path = "../../early-boot-config-provider", version = "0.1" }

[build-dependencies]
generate-readme = { version = "0.1", path = "../../../generate-readme" }
