[package]
name = "libdbus"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
releases-url = "https://dbus.freedesktop.org/releases/dbus"

[[package.metadata.build-package.external-files]]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.15.4.tar.xz"
sha512 = "53a5b7161940c5d4432b902c3c0ac1f1965978e3791a640d1a71f2d819474b727497f7a13c95d7c5850baef659062f1434296a3f5e56701383cc573dfbf187ee"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libexpat = { path = "../libexpat" }
