[package]
name = "metal-dev"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-layout]
partition-plan = "unified"

[package.metadata.build-variant.image-features]
grub-set-private-var = true
xfs-data-partition = true
uefi-secure-boot = true
systemd-networkd = true

[package.metadata.build-variant]
image-format = "raw"
kernel-parameters = [
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M"
]
included-packages = [
# core
    "release",
    "kernel-6.1",
    "linux-firmware",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
# tools
    "login",
    "iputils",
    "strace",
    "chrony-tools",
]

[lib]
path = "../variants.rs"

[build-dependencies]
settings-defaults = { path = "../../packages/settings-defaults" }
settings-plugins = { path = "../../packages/settings-plugins" }
