[package]
name = "sundog"
version = "0.1.0"
authors = ["mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
apiserver = { path = "../apiserver" }
http = "0.2"
log = "0.4"
models = { path = "../../models" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.7"
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
