[package]
name = "netdog"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
dns-lookup = "1.0"
ipnet = { version = "2.0", features = ["serde"] }
envy = "0.4"
lazy_static = "1.2"
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
