[package]
name = "ecs-settings-applier"
version = "0.1.0"
authors = ["Samuel Karp <skarp@amazon.com>"]
license = "Apache-2.0 OR MIT"
publish = false
edition = "2018"
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
constants = { path = "../../constants", version = "0.1.0" }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
schnauzer = { path = "../schnauzer", version = "0.1.0" }
log = "0.4"
models = { path = "../../models", version = "0.1.0" }
simplelog = "0.11"
snafu = "0.7"
tokio = { version = "~1.14", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
buildsys = { path = "../../../tools/buildsys", version = "0.1.0" }
cargo-readme = "3.1"
