[package]
name = "ecs-settings-applier"
version = "0.1.0"
authors = ["Samuel Karp <skarp@amazon.com>"]
license = "Apache-2.0 OR MIT"
publish = false
edition = "2021"
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
constants = { path = "../../constants", version = "0.1" }
serde = {version = "1", features = ["derive"]}
serde_json = "1"
schnauzer = { path = "../schnauzer", version = "0.1" }
log = "0.4"
models = { path = "../../models", version = "0.1" }
simplelog = "0.12"
snafu = "0.7"
tokio = { version = "~1.25", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
bottlerocket-variant = { version = "0.1", path = "../../bottlerocket-variant" }
generate-readme = { version = "0.1", path = "../../generate-readme" }
