[package]
# This is the metal-k8s-1.27 variant. "." is not allowed in crate names, but
# we don't use this crate name anywhere.
name = "metal-k8s-1_27"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-layout]
os-image-size-gib = 4
partition-plan = "unified"

[package.metadata.build-variant.image-features]
grub-set-private-var = true
unified-cgroup-hierarchy = true

[package.metadata.build-variant]
image-format = "raw"
supported-arches = ["x86_64"]
kernel-parameters = [
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M"
]
included-packages = [
    "aws-iam-authenticator",
    "cni",
    "cni-plugins",
    "kernel-5.15",
    "linux-firmware",
    "kubelet-1.27",
    "release",
]

[lib]
path = "../variants.rs"

[build-dependencies]
aws-iam-authenticator = { path = "../../packages/aws-iam-authenticator" }
cni = { path = "../../packages/cni" }
cni-plugins = { path = "../../packages/cni-plugins" }
kernel-5_15 = { path = "../../packages/kernel-5.15" }
linux-firmware = { path = "../../packages/linux-firmware" }
kubernetes-1_27 = { path = "../../packages/kubernetes-1.27" }
release = { path = "../../packages/release" }
