[package]
name = "aws-dev"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]
grub-features = [
    "set-private-var"
]
included-packages = [
# core
    "release",
    "kernel-5.15",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
    "docker-proxy",
# tools
    "login",
    "iputils",
    "strace",
    "tcpdump",
    "chrony-tools",
]

[lib]
path = "lib.rs"

[build-dependencies]
# core
release = { path = "../../packages/release" }
kernel-5_15 = { path = "../../packages/kernel-5.15" }
# docker
docker-cli = { path = "../../packages/docker-cli" }
docker-engine = { path = "../../packages/docker-engine" }
docker-init = { path = "../../packages/docker-init" }
docker-proxy = { path = "../../packages/docker-proxy" }
# tools
login = { path = "../../packages/login" }
iputils = { path = "../../packages/iputils" }
strace = { path = "../../packages/strace" }
tcpdump = { path = "../../packages/tcpdump" }
chrony = { path = "../../packages/chrony" }
