[package]
name = "aws-dev"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant.image-features]
grub-set-private-var = true
unified-cgroup-hierarchy = true
xfs-data-partition = true
uefi-secure-boot = true
systemd-networkd = true

[package.metadata.build-variant]
kernel-parameters = [
    "console=tty0",
    "console=ttyS0,115200n8",
    # Only reserve if there are at least 2GB
    "crashkernel=2G-:256M",
    "net.ifnames=0",
    "netdog.default-interface=eth0:dhcp4,dhcp6?",
    "quiet",
]
included-packages = [
# core
    "early-boot-config",
    "release",
    "kernel-6.1",
    "aws-data-providers",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
# tools
    "login",
    "iputils",
    "strace",
    "chrony-tools",
]

[lib]
path = "../variants.rs"

[build-dependencies]
# core
early-boot-config = { path = "../../packages/early-boot-config" }
early-boot-config-ec2-identity-doc = { path = "../../packages/early-boot-config-ec2-identity-doc" }
early-boot-config-ec2-imds = { path = "../../packages/early-boot-config-ec2-imds" }
early-boot-config-local-defaults = { path = "../../packages/early-boot-config-local-defaults" }
early-boot-config-local-overrides = { path = "../../packages/early-boot-config-local-overrides" }
early-boot-config-local = { path = "../../packages/early-boot-config-local" }
early-boot-config-providers = { path = "../../packages/early-boot-config-providers" }
release = { path = "../../packages/release" }
kernel-6_1 = { path = "../../packages/kernel-6.1" }
# docker
docker-cli = { path = "../../packages/docker-cli" }
docker-engine = { path = "../../packages/docker-engine" }
docker-init = { path = "../../packages/docker-init" }
# tools
login = { path = "../../packages/login" }
iputils = { path = "../../packages/iputils" }
strace = { path = "../../packages/strace" }
chrony = { path = "../../packages/chrony" }
