[package]
name = "settings-committer"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
snafu = "0.6"
http = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.7"

[build-dependencies]
cargo-readme = "3.1"
