[package]
name = "nvidia-container-toolkit"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/nvidia-container-toolkit/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/nvidia-container-toolkit/archive/v1.13.1/nvidia-container-toolkit-1.13.1.tar.gz"
sha512 = "e0d9dbb06e2b8ef075a881f4414bfb4b1ab9f571d148a202fbf7c2a7b59447f199028d5d176196703dadcb04040a74a229f09062da24e615faa4c051d614e206"

[build-dependencies]
glibc = { path = "../glibc" }
libnvidia-container = { path = "../libnvidia-container" }
# This package depends on `shimpei`, but it is built in the `os` package
# which is expected to be pulled in
# os = { path = "../os" }
