[configuration-files.containerd-config-toml]
# No override to path
template-path = "/usr/share/templates/containerd-config-toml_aws-dev"

# Docker
[services.docker]
restart-commands = ["/bin/systemctl try-restart docker.service"]
configuration-files = ["proxy-env"]

# Metrics
[settings.metrics]
send-metrics = false
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "docker"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "docker", "host-containerd", "host-containers"]
