[package]
name = "testsys"
version = "0.1.0"
authors = ["Ethan Pullen <pullenep@amazon.com>", "Matt Briggs <brigmatt@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
aws-config = "0.55"
aws-sdk-ec2 = "0.28"
base64 = "0.20"
bottlerocket-types = { git = "https://github.com/bottlerocket-os/bottlerocket-test-system", version = "0.0.8", tag = "v0.0.8"}
bottlerocket-variant = { version = "0.1", path = "../../sources/bottlerocket-variant" }
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
futures = "0.3"
handlebars = "4"
log = "0.4"
maplit = "1"
testsys-model = { git = "https://github.com/bottlerocket-os/bottlerocket-test-system", version = "0.0.8", tag = "v0.0.8"}
pubsys-config = { path = "../pubsys-config/", version = "0.1.0" }
fastrand = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
serde_yaml = "0.9"
snafu = "0.7"
term_size = "0.3"
testsys-config = { path = "../testsys-config/", version = "0.1" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
unescape = "0.1"
url = "2"
