[package]
name = "libnetfilter_cthelper"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnetfilter_cthelper/files"

[[package.metadata.build-package.external-files]]
url = "https://netfilter.org/projects/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0.tar.bz2"
sha512 = "f0372daee0edbf4c27ee80eadd4ce786a4b67b39c0b9d22e88bc9adcbdffd6676eb9df01b933ee64d2fcea9c05a9ca9070c94e907277d69acbd22ae9a3c74e45"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
