[package]
name = "workspaces"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = true
source-groups = [
    "api",
    "bottlerocket-release",
    "growpart",
    "updater",
    "webpki-roots-shim",
    "models",
    "preinit",
]

[lib]
path = "pkg.rs"

[build-dependencies]
glibc = { path = "../glibc" }
