[package]
name = "libnftnl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnftnl/files"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnftnl/files/libnftnl-1.2.5.tar.xz"
sha512 = "576ccd0815063a6ef3095b5514c3d286b4450fad98fbf7a85cd537f66adf043e7e6295d4c84cc3cbfd18cf9a29576d15a88cc439a61a3e654841a27c71babea1"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
