[package]
name = "early-boot-config"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient", version = "0.1.0" }
async-trait = "0.1.36"
base64 = "0.13"
constants = { path = "../../constants", version = "0.1.0" }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
http = "0.2"
imdsclient = { path = "../../imdsclient", version = "0.1.0" }
log = "0.4"
retry-read = { path = "../../retry-read", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_plain = "1.0"
serde-xml-rs = "0.5"
simplelog = "0.11"
snafu = "0.7"
tokio = { version = "~1.16", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS
toml = "0.5"

[target.'cfg(target_arch = "x86_64")'.dependencies]
# vmw_backdoor includes x86_64 assembly, prevent it from building for ARM
vmw_backdoor = "0.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
hex-literal = "0.3"
lazy_static = "1.4"
