[package]
name = "settings-migrations"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
source-groups = [
    "settings-migrations"
]

# RPM BuildRequires
[build-dependencies]

# RPM Requires
[dependencies]
