[package]
name = "os"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = true
source-groups = [
    "api",
    "bottlerocket-release",
    "metricdog",
    "parse-datetime",
    "ghostdog",
    "growpart",
    "updater",
    "webpki-roots-shim",
    "logdog",
    "models",
    "imdsclient",
    "retry-read",
    "shimpei",
    "driverdog",
    "cfsignal",
]

[lib]
path = "pkg.rs"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# We depend on these packages at runtime, and are expected to be pulled in
# by way of the `release` package.
# `host-ctr` for host containers functionality
# host-ctr = { path = "../host-ctr" }
# kexec-tools and makedumpfile required for prairiedog functionality
# kexec-tools = { path = "../kexec-tools" }
# makedumpfile = { path = "../makedumpfile" }
# binutils required for driverdog functionality
# binutils = { path = "../binutils" }
# oci-add-hooks required for shimpei functionality
# oci-add-hooks = { path = "../oci-add-hooks" }
