[workspace]
members = [
    "acpid",
    "aws-iam-authenticator",
    "bash",
    "ca-certificates",
    "chrony",
    "cni",
    "cni-plugins",
    "conntrack-tools",
    "containerd",
    "coreutils",
    "dbus-broker",
    "docker-cli",
    "docker-engine",
    "docker-init",
    "docker-proxy",
    "filesystem",
    "findutils",
    "glibc",
    "grub",
    "host-ctr",
    "iproute",
    "iptables",
    "iputils",
    "kernel",
    "kmod",
    "kubernetes-1.15",
    "kubernetes-1.16",
    "libacl",
    "libattr",
    "libaudit",
    "libcap",
    "libdbus",
    "libgcc",
    "libexpat",
    "libiw",
    "libmnl",
    "libnetfilter_conntrack",
    "libnetfilter_cthelper",
    "libnetfilter_cttimeout",
    "libnetfilter_queue",
    "libnfnetlink",
    "libnftnl",
    "libnl",
    "libpcap",
    "libpcre",
    "libseccomp",
    "libsepol",
    "libselinux",
    "libstd-rust",
    "libxcrypt",
    "login",
    "ncurses",
    "procps",
    "readline",
    "release",
    "runc",
    "selinux-policy",
    "socat",
    "strace",
    "systemd",
    "tcpdump",
    "util-linux",
    "wicked",
    "os",
]

[profile.dev]
debug = false
opt-level = 'z'
