[workspace]
members = [
    "api",
    "aws-iam-authenticator",
    "bash",
    "ca-certificates",
    "chrony",
    "cni",
    "cni-plugins",
    "conntrack-tools",
    "containerd",
    "coreutils",
    "cri-tools",
    "dbus-broker",
    "docker-cli",
    "docker-engine",
    "docker-init",
    "docker-proxy",
    "filesystem",
    "glibc",
    "golang",
    "grub",
    "host-containers",
    "iproute",
    "iptables",
    "kernel",
    "kmod",
    "kubernetes",
    "libacl",
    "libattr",
    "libcap",
    "libdbus",
    "libexpat",
    "libiw",
    "libmnl",
    "libnetfilter_conntrack",
    "libnetfilter_cthelper",
    "libnetfilter_cttimeout",
    "libnetfilter_queue",
    "libnfnetlink",
    "libnftnl",
    "libnl",
    "libseccomp",
    "libxcrypt",
    "ncurses",
    "preinit",
    "readline",
    "release",
    "runc",
    "rust",
    "sdk",
    "socat",
    "ssm",
    "strace",
    "systemd",
    "updater",
    "util-linux",
    "wicked",
]

[profile.dev]
debug = false
opt-level = 'z'
