[package]
name = "corndog"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient", version = "0.1" }
constants = { path = "../../constants", version = "0.1" }
http = "0.2"
log = "0.4"
models = { path = "../../models", version = "0.1" }
serde_json = "1"
simplelog = "0.12"
snafu = "0.7"
tokio = { version = "~1.25", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }
