[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "(Apache-2.0 OR MIT) AND MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bytes = "1"
constants = { path = "../../constants", version = "0.1" }
futures-util = { version = "0.3", default-features = false }
headers = "0.3"
http = "0.2"
hyper = "0.14"
hyper-rustls = { version = "0.24", default-features = false, features = ["http2", "native-tokio", "tls12", "logging"] }
imdsclient = { path = "../../imdsclient", version = "0.1" }
modeled-types = { path = "../../models/modeled-types", version = "0.1" }
aws-config = "1"
aws-sdk-eks = "1"
aws-sdk-ec2 = "1"
aws-types = "1"
aws-smithy-types = "1"
aws-smithy-runtime = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snafu = "0.8"
tokio = { version = "~1.32", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS
tokio-retry = "0.3"
tokio-rustls = "0.24"
url = "2"
log = "0.4.21"

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }
