[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient", version = "0.1.0" }
constants = { path = "../../constants", version = "0.1.0" }
hyper = "0.14.2"
hyper-proxy = {  version = "0.9", default-features = false, features = ["rustls"] }
hyper-rustls = "0.23"
imdsclient = { path = "../../imdsclient", version = "0.1.0" }
models = { path = "../../models", version = "0.1.0" }
rusoto_core = { version = "0.48.0", default-features = false, features = ["rustls"] }
rusoto_eks = { version = "0.48.0", default-features = false, features = ["rustls"] }
serde_json = "1"
snafu = "0.7"
tokio = { version = "~1.14", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
bottlerocket-variant = { version = "0.1", path = "../../bottlerocket-variant" }
generate-readme = { version = "0.1", path = "../../generate-readme" }
