[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient", version = "0.1" }
constants = { path = "../../constants", version = "0.1" }
hyper = "0.14"
hyper-proxy = {  version = "0.9", default-features = false, features = ["rustls"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http2", "native-tokio", "tls12", "logging"] }
imdsclient = { path = "../../imdsclient", version = "0.1" }
models = { path = "../../models", version = "0.1" }
aws-config = "0.54"
aws-sdk-eks = "0.24"
aws-types = "0.54"
aws-smithy-client = { version = "0.54", default-features = false, features = ["rustls"] }
serde_json = "1"
snafu = "0.7"
tokio = { version = "~1.25", default-features = false, features = ["macros", "rt-multi-thread"] }  # LTS

[build-dependencies]
bottlerocket-variant = { version = "0.1", path = "../../bottlerocket-variant" }
generate-readme = { version = "0.1", path = "../../generate-readme" }
