[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
lazy_static = "1.4"
reqwest = { version = "0.11.1", default-features = false, features = ["blocking"]}
serde_json = "1"
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
