[package]
name = "libzstd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/facebook/zstd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/facebook/zstd/releases/download/v1.5.4/zstd-1.5.4.tar.gz"
sha512 = "2896a6dd6b60cc251720356babcbab6018c874eb2149121b26e28041496fc355a9cb5fd1b39c91558fcfbafb789b3d721264a0f9b5734f893d5f3cdf97016394"

[build-dependencies]
glibc = { path = "../glibc" }
