[package]
name = "vmware-dev"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[package.metadata.build-variant]
included-packages = [
# core
    "release",
# docker
    "docker-cli",
    "docker-engine",
    "docker-init",
    "docker-proxy",
# tools
    "findutils",
    "login",
    "iputils",
    "procps",
    "strace",
    "tcpdump",
    "chrony-tools",
]

[lib]
path = "lib.rs"
